// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_registry.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListAllServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllServicesRequest) Reset()         { *m = ListAllServicesRequest{} }
func (m *ListAllServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllServicesRequest) ProtoMessage()    {}
func (*ListAllServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{0}
}

func (m *ListAllServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllServicesRequest.Unmarshal(m, b)
}
func (m *ListAllServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListAllServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllServicesRequest.Merge(m, src)
}
func (m *ListAllServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListAllServicesRequest.Size(m)
}
func (m *ListAllServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllServicesRequest proto.InternalMessageInfo

type ListAllServicesResponse struct {
	Services             []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllServicesResponse) Reset()         { *m = ListAllServicesResponse{} }
func (m *ListAllServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllServicesResponse) ProtoMessage()    {}
func (*ListAllServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{1}
}

func (m *ListAllServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllServicesResponse.Unmarshal(m, b)
}
func (m *ListAllServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListAllServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllServicesResponse.Merge(m, src)
}
func (m *ListAllServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListAllServicesResponse.Size(m)
}
func (m *ListAllServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllServicesResponse proto.InternalMessageInfo

func (m *ListAllServicesResponse) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type FindServicesRequest struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindServicesRequest) Reset()         { *m = FindServicesRequest{} }
func (m *FindServicesRequest) String() string { return proto.CompactTextString(m) }
func (*FindServicesRequest) ProtoMessage()    {}
func (*FindServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{2}
}

func (m *FindServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindServicesRequest.Unmarshal(m, b)
}
func (m *FindServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindServicesRequest.Marshal(b, m, deterministic)
}
func (m *FindServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindServicesRequest.Merge(m, src)
}
func (m *FindServicesRequest) XXX_Size() int {
	return xxx_messageInfo_FindServicesRequest.Size(m)
}
func (m *FindServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindServicesRequest proto.InternalMessageInfo

func (m *FindServicesRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type FindServicesResponse struct {
	Services             []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindServicesResponse) Reset()         { *m = FindServicesResponse{} }
func (m *FindServicesResponse) String() string { return proto.CompactTextString(m) }
func (*FindServicesResponse) ProtoMessage()    {}
func (*FindServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{3}
}

func (m *FindServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindServicesResponse.Unmarshal(m, b)
}
func (m *FindServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindServicesResponse.Marshal(b, m, deterministic)
}
func (m *FindServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindServicesResponse.Merge(m, src)
}
func (m *FindServicesResponse) XXX_Size() int {
	return xxx_messageInfo_FindServicesResponse.Size(m)
}
func (m *FindServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindServicesResponse proto.InternalMessageInfo

func (m *FindServicesResponse) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type GetAddressRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressRequest) Reset()         { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()    {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{4}
}

func (m *GetAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressRequest.Unmarshal(m, b)
}
func (m *GetAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressRequest.Merge(m, src)
}
func (m *GetAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddressRequest.Size(m)
}
func (m *GetAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressRequest proto.InternalMessageInfo

func (m *GetAddressRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type GetAddressResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressResponse) Reset()         { *m = GetAddressResponse{} }
func (m *GetAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetAddressResponse) ProtoMessage()    {}
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{5}
}

func (m *GetAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressResponse.Unmarshal(m, b)
}
func (m *GetAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressResponse.Merge(m, src)
}
func (m *GetAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetAddressResponse.Size(m)
}
func (m *GetAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressResponse proto.InternalMessageInfo

func (m *GetAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetHTTPServerAddressRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHTTPServerAddressRequest) Reset()         { *m = GetHTTPServerAddressRequest{} }
func (m *GetHTTPServerAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetHTTPServerAddressRequest) ProtoMessage()    {}
func (*GetHTTPServerAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{6}
}

func (m *GetHTTPServerAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHTTPServerAddressRequest.Unmarshal(m, b)
}
func (m *GetHTTPServerAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHTTPServerAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetHTTPServerAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHTTPServerAddressRequest.Merge(m, src)
}
func (m *GetHTTPServerAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetHTTPServerAddressRequest.Size(m)
}
func (m *GetHTTPServerAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHTTPServerAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHTTPServerAddressRequest proto.InternalMessageInfo

func (m *GetHTTPServerAddressRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type GetHTTPServerAddressResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHTTPServerAddressResponse) Reset()         { *m = GetHTTPServerAddressResponse{} }
func (m *GetHTTPServerAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetHTTPServerAddressResponse) ProtoMessage()    {}
func (*GetHTTPServerAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{7}
}

func (m *GetHTTPServerAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHTTPServerAddressResponse.Unmarshal(m, b)
}
func (m *GetHTTPServerAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHTTPServerAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetHTTPServerAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHTTPServerAddressResponse.Merge(m, src)
}
func (m *GetHTTPServerAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetHTTPServerAddressResponse.Size(m)
}
func (m *GetHTTPServerAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHTTPServerAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHTTPServerAddressResponse proto.InternalMessageInfo

func (m *GetHTTPServerAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetAnnotationRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Annotation           string   `protobuf:"bytes,2,opt,name=annotation,proto3" json:"annotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnotationRequest) Reset()         { *m = GetAnnotationRequest{} }
func (m *GetAnnotationRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationRequest) ProtoMessage()    {}
func (*GetAnnotationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{8}
}

func (m *GetAnnotationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationRequest.Unmarshal(m, b)
}
func (m *GetAnnotationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationRequest.Marshal(b, m, deterministic)
}
func (m *GetAnnotationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationRequest.Merge(m, src)
}
func (m *GetAnnotationRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationRequest.Size(m)
}
func (m *GetAnnotationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationRequest proto.InternalMessageInfo

func (m *GetAnnotationRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *GetAnnotationRequest) GetAnnotation() string {
	if m != nil {
		return m.Annotation
	}
	return ""
}

type GetAnnotationResponse struct {
	AnnotationValue      string   `protobuf:"bytes,1,opt,name=annotation_value,json=annotationValue,proto3" json:"annotation_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnnotationResponse) Reset()         { *m = GetAnnotationResponse{} }
func (m *GetAnnotationResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnnotationResponse) ProtoMessage()    {}
func (*GetAnnotationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c28293224e66671, []int{9}
}

func (m *GetAnnotationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnnotationResponse.Unmarshal(m, b)
}
func (m *GetAnnotationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnnotationResponse.Marshal(b, m, deterministic)
}
func (m *GetAnnotationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnnotationResponse.Merge(m, src)
}
func (m *GetAnnotationResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnnotationResponse.Size(m)
}
func (m *GetAnnotationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnnotationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnnotationResponse proto.InternalMessageInfo

func (m *GetAnnotationResponse) GetAnnotationValue() string {
	if m != nil {
		return m.AnnotationValue
	}
	return ""
}

func init() {
	proto.RegisterType((*ListAllServicesRequest)(nil), "magma.orc8r.service_registry.ListAllServicesRequest")
	proto.RegisterType((*ListAllServicesResponse)(nil), "magma.orc8r.service_registry.ListAllServicesResponse")
	proto.RegisterType((*FindServicesRequest)(nil), "magma.orc8r.service_registry.FindServicesRequest")
	proto.RegisterType((*FindServicesResponse)(nil), "magma.orc8r.service_registry.FindServicesResponse")
	proto.RegisterType((*GetAddressRequest)(nil), "magma.orc8r.service_registry.GetAddressRequest")
	proto.RegisterType((*GetAddressResponse)(nil), "magma.orc8r.service_registry.GetAddressResponse")
	proto.RegisterType((*GetHTTPServerAddressRequest)(nil), "magma.orc8r.service_registry.GetHTTPServerAddressRequest")
	proto.RegisterType((*GetHTTPServerAddressResponse)(nil), "magma.orc8r.service_registry.GetHTTPServerAddressResponse")
	proto.RegisterType((*GetAnnotationRequest)(nil), "magma.orc8r.service_registry.GetAnnotationRequest")
	proto.RegisterType((*GetAnnotationResponse)(nil), "magma.orc8r.service_registry.GetAnnotationResponse")
}

func init() { proto.RegisterFile("service_registry.proto", fileDescriptor_7c28293224e66671) }

var fileDescriptor_7c28293224e66671 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xad, 0x06, 0x81, 0x89, 0x06, 0x5d, 0x11, 0x9b, 0x4a, 0x0c, 0xd9, 0x13, 0xc6, 0x58,
	0xb5, 0x48, 0x44, 0x6f, 0x70, 0x10, 0x0f, 0x1e, 0x48, 0x25, 0x1e, 0xbc, 0x90, 0x05, 0x36, 0xa4,
	0x49, 0x69, 0x61, 0x77, 0xc1, 0xe8, 0xc9, 0x5f, 0xa0, 0x7f, 0xd9, 0x40, 0xb7, 0x05, 0x0a, 0x52,
	0xea, 0xa9, 0x99, 0x99, 0x37, 0xef, 0x4d, 0xd3, 0x2f, 0x85, 0x1c, 0xa7, 0x6c, 0x6c, 0x75, 0x68,
	0x8b, 0xd1, 0x9e, 0xc5, 0x05, 0xfb, 0xd0, 0x07, 0xcc, 0x15, 0x2e, 0xca, 0xf7, 0x49, 0xaf, 0x4f,
	0x74, 0x97, 0x75, 0x2a, 0x4c, 0x0f, 0x6b, 0xb0, 0x0a, 0xb9, 0x67, 0x8b, 0x8b, 0xaa, 0x6d, 0xbf,
	0x78, 0x23, 0x6e, 0xd2, 0xe1, 0x88, 0x72, 0x81, 0xcb, 0x70, 0xb2, 0x34, 0xe1, 0x03, 0xd7, 0xe1,
	0x14, 0x69, 0x90, 0x92, 0x46, 0x5c, 0x55, 0x0a, 0x3b, 0xc5, 0xb4, 0x19, 0xd4, 0xf8, 0x02, 0x8e,
	0x1e, 0x2d, 0xa7, 0x1b, 0x72, 0x43, 0x59, 0x48, 0xd8, 0xa4, 0x4d, 0x6d, 0x55, 0x29, 0x28, 0xc5,
	0xb4, 0xe9, 0x15, 0xd8, 0x80, 0xec, 0xa2, 0x78, 0x83, 0x80, 0x4b, 0x38, 0xac, 0x53, 0x51, 0xed,
	0x76, 0x19, 0xe5, 0x81, 0xbd, 0x0a, 0x49, 0x29, 0x90, 0x01, 0x7e, 0x89, 0x75, 0x40, 0xf3, 0x72,
	0x19, 0xa0, 0x42, 0x92, 0x78, 0x2d, 0x5f, 0x2f, 0x4b, 0x7c, 0x07, 0xa7, 0x75, 0x2a, 0x9e, 0x9a,
	0xcd, 0xc6, 0xe4, 0x2a, 0xca, 0x36, 0x0e, 0xaa, 0x40, 0x7e, 0xf5, 0x62, 0x64, 0x64, 0x03, 0xb2,
	0x93, 0x13, 0x1d, 0xc7, 0x15, 0x44, 0x58, 0xae, 0x13, 0x99, 0x85, 0xce, 0x00, 0x48, 0x20, 0x57,
	0xb7, 0xa7, 0xc3, 0xb9, 0x0e, 0xae, 0xc1, 0x71, 0xc8, 0x51, 0x1e, 0x71, 0x0e, 0x07, 0x33, 0x59,
	0x6b, 0x4c, 0xec, 0x91, 0xef, 0x9d, 0x99, 0xf5, 0x5f, 0x27, 0x6d, 0xe3, 0x3b, 0x01, 0x19, 0xf9,
	0x61, 0x4c, 0x49, 0x0b, 0xfa, 0x52, 0x20, 0x13, 0x82, 0x02, 0xdd, 0xea, 0xeb, 0x00, 0xd3, 0x57,
	0xd3, 0xa5, 0x95, 0x63, 0x6e, 0x79, 0xf7, 0xe3, 0x2d, 0xf4, 0x0e, 0x7b, 0xf3, 0xc8, 0xa0, 0x9b,
	0xf5, 0x46, 0x2b, 0x58, 0xd4, 0x8c, 0x38, 0x2b, 0x41, 0xf0, 0x10, 0x60, 0x06, 0x12, 0xba, 0x5a,
	0xef, 0xb1, 0x44, 0xa8, 0x76, 0xbd, 0xf9, 0x42, 0x10, 0xf9, 0xa3, 0x4c, 0xc9, 0x58, 0x62, 0x0a,
	0xdd, 0x47, 0x9a, 0xfd, 0x05, 0xb0, 0xf6, 0xf0, 0x9f, 0xd5, 0xe0, 0xa2, 0x4f, 0xd8, 0x5f, 0x00,
	0x0b, 0x19, 0xd1, 0xaf, 0x15, 0xe6, 0x5a, 0x2b, 0xc5, 0xda, 0xf1, 0xb3, 0x6b, 0xa9, 0xb7, 0xdd,
	0xe9, 0x1f, 0x8d, 0xb7, 0xbd, 0x67, 0xe9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x81, 0xbf, 0xa9,
	0xf3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceRegistryClient is the client API for ServiceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceRegistryClient interface {
	// ListAllServices returns the service name of all services in the registry.
	ListAllServices(ctx context.Context, in *ListAllServicesRequest, opts ...grpc.CallOption) (*ListAllServicesResponse, error)
	// FindServices returns the names of all services that have the passed label.
	FindServices(ctx context.Context, in *FindServicesRequest, opts ...grpc.CallOption) (*FindServicesResponse, error)
	// GetAddress returns the service address of a given service.
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
	// GetHTTPServerAddress returns the address for a service's HTTP server.
	GetHTTPServerAddress(ctx context.Context, in *GetHTTPServerAddressRequest, opts ...grpc.CallOption) (*GetHTTPServerAddressResponse, error)
	// GetAnnotation returns the annotation value for the passed annotation
	// name.
	GetAnnotation(ctx context.Context, in *GetAnnotationRequest, opts ...grpc.CallOption) (*GetAnnotationResponse, error)
}

type serviceRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceRegistryClient(cc grpc.ClientConnInterface) ServiceRegistryClient {
	return &serviceRegistryClient{cc}
}

func (c *serviceRegistryClient) ListAllServices(ctx context.Context, in *ListAllServicesRequest, opts ...grpc.CallOption) (*ListAllServicesResponse, error) {
	out := new(ListAllServicesResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.service_registry.ServiceRegistry/ListAllServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) FindServices(ctx context.Context, in *FindServicesRequest, opts ...grpc.CallOption) (*FindServicesResponse, error) {
	out := new(FindServicesResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.service_registry.ServiceRegistry/FindServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	out := new(GetAddressResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.service_registry.ServiceRegistry/GetAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetHTTPServerAddress(ctx context.Context, in *GetHTTPServerAddressRequest, opts ...grpc.CallOption) (*GetHTTPServerAddressResponse, error) {
	out := new(GetHTTPServerAddressResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.service_registry.ServiceRegistry/GetHTTPServerAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetAnnotation(ctx context.Context, in *GetAnnotationRequest, opts ...grpc.CallOption) (*GetAnnotationResponse, error) {
	out := new(GetAnnotationResponse)
	err := c.cc.Invoke(ctx, "/magma.orc8r.service_registry.ServiceRegistry/GetAnnotation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServer is the server API for ServiceRegistry service.
type ServiceRegistryServer interface {
	// ListAllServices returns the service name of all services in the registry.
	ListAllServices(context.Context, *ListAllServicesRequest) (*ListAllServicesResponse, error)
	// FindServices returns the names of all services that have the passed label.
	FindServices(context.Context, *FindServicesRequest) (*FindServicesResponse, error)
	// GetAddress returns the service address of a given service.
	GetAddress(context.Context, *GetAddressRequest) (*GetAddressResponse, error)
	// GetHTTPServerAddress returns the address for a service's HTTP server.
	GetHTTPServerAddress(context.Context, *GetHTTPServerAddressRequest) (*GetHTTPServerAddressResponse, error)
	// GetAnnotation returns the annotation value for the passed annotation
	// name.
	GetAnnotation(context.Context, *GetAnnotationRequest) (*GetAnnotationResponse, error)
}

// UnimplementedServiceRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedServiceRegistryServer struct {
}

func (*UnimplementedServiceRegistryServer) ListAllServices(ctx context.Context, req *ListAllServicesRequest) (*ListAllServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllServices not implemented")
}
func (*UnimplementedServiceRegistryServer) FindServices(ctx context.Context, req *FindServicesRequest) (*FindServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindServices not implemented")
}
func (*UnimplementedServiceRegistryServer) GetAddress(ctx context.Context, req *GetAddressRequest) (*GetAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (*UnimplementedServiceRegistryServer) GetHTTPServerAddress(ctx context.Context, req *GetHTTPServerAddressRequest) (*GetHTTPServerAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHTTPServerAddress not implemented")
}
func (*UnimplementedServiceRegistryServer) GetAnnotation(ctx context.Context, req *GetAnnotationRequest) (*GetAnnotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnnotation not implemented")
}

func RegisterServiceRegistryServer(s *grpc.Server, srv ServiceRegistryServer) {
	s.RegisterService(&_ServiceRegistry_serviceDesc, srv)
}

func _ServiceRegistry_ListAllServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).ListAllServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.service_registry.ServiceRegistry/ListAllServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).ListAllServices(ctx, req.(*ListAllServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_FindServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).FindServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.service_registry.ServiceRegistry/FindServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).FindServices(ctx, req.(*FindServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.service_registry.ServiceRegistry/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetAddress(ctx, req.(*GetAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetHTTPServerAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHTTPServerAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetHTTPServerAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.service_registry.ServiceRegistry/GetHTTPServerAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetHTTPServerAddress(ctx, req.(*GetHTTPServerAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.orc8r.service_registry.ServiceRegistry/GetAnnotation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetAnnotation(ctx, req.(*GetAnnotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.orc8r.service_registry.ServiceRegistry",
	HandlerType: (*ServiceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllServices",
			Handler:    _ServiceRegistry_ListAllServices_Handler,
		},
		{
			MethodName: "FindServices",
			Handler:    _ServiceRegistry_FindServices_Handler,
		},
		{
			MethodName: "GetAddress",
			Handler:    _ServiceRegistry_GetAddress_Handler,
		},
		{
			MethodName: "GetHTTPServerAddress",
			Handler:    _ServiceRegistry_GetHTTPServerAddress_Handler,
		},
		{
			MethodName: "GetAnnotation",
			Handler:    _ServiceRegistry_GetAnnotation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_registry.proto",
}
